### ISSUE TITLE
餐廳明細滑動tab

### ISSUE THREAD

**Issue by shihKaiHung** [thereazon/vue-app#61]
<img width="256" alt="Screen Shot 2022-07-01 at 10 36 29 PM" src="https://user-images.githubusercontent.com/15310175/176915345-e8d58cfb-9ead-4151-8790-979ff5b8d69d.png">

https://user-images.githubusercontent.com/15310175/176915705-8b9d2d4a-0aa2-4529-a221-a93bd872876b.MOV

note: 
裡面卡片組件不包含在這張單的內容裡面
這張單工作只有那4個tab功能跟切換tab底下頁面要跟著變動

tab需要可以用滑動的，可以找找套件

**Comment by grasdira** [comment]
> 

@shihKaiHung 請問這個tab是直接新增在 src\views\Dispatch\RestaurantList\index.vue 嗎?

**Comment by shihKaiHung** [comment]
> > 
> 
> @shihKaiHung 請問這個tab是直接新增在 src\views\Dispatch\RestaurantList\index.vue 嗎?

對唷 寫在這頁面就可以了
