### ISSUE TITLE
餐廳溫度確認頁面

### ISSUE THREAD

**Issue by shihKaiHung** [thereazon/vue-app#64]
<img width="293" alt="Screen Shot 2022-07-01 at 10 52 10 PM" src="https://user-images.githubusercontent.com/15310175/176918271-1cf01cee-84ef-4c36-ace6-e98e47e1f6b2.png">

Note: 
1. 上方卡片不需要做，卡片有另外開別張issue了

2. 中間的溫度表在precool頁面也有相同的組件可以照搬過去

<img width="214" alt="Screen Shot 2022-07-01 at 10 52 59 PM" src="https://user-images.githubusercontent.com/15310175/176918420-8f1fc011-c46f-4a1a-8414-b00a42abc227.png">

邏輯: 
1. 點選擷取溫度會去call api並把目前溫度那裡填上api回來的溫度
2. 點選櫃檯實測溫度會彈跳出實測溫度的modal可以填寫
<img width="261" alt="Screen Shot 2022-07-01 at 10 55 16 PM" src="https://user-images.githubusercontent.com/15310175/176918812-6d698702-c96e-48b7-85fc-874b2cee4a6f.png">

影片參考：私訊丟

**Comment by abe1272001** [comment]
<img width="293" alt="176918271-1cf01cee-84ef-4c36-ace6-e98e47e1f6b2" src="https://user-images.githubusercontent.com/46858104/176989256-4ad2d993-d8ed-49d1-9007-571080319a61.png">

@shihKaiHung 請問點選這兩個紅匡都是彈跳實測溫度的 modal 嗎？
