### ISSUE TITLE
餐廳溫度確認頁面商業邏輯＆api串接

### ISSUE THREAD

**Issue by shihKaiHung** [thereazon/vue-app#77]
<img width="1197" alt="Screen Shot 2022-07-20 at 11 29 04 AM" src="https://user-images.githubusercontent.com/15310175/179890244-1e387b20-e0eb-449f-a7f5-1ffd5358d9f1.png">

### 需求

參考swagger /webStore/

1. 需鎖定溫度以及拍照完，完成button才能點擊 
2. 點擊鎖定溫度後即不可以再改溫度 -> 鎖定溫度api （ /api/webStore/{id}/temperature 餐廳鎖定溫度）
3. 送出api -> ​（/api​/webStore​/{id}​/temperature_finish 餐廳溫度完成)
4. 擷取溫度須call  ( /api/car/{id}/temperature 車子即時溫度) 可以參考預冷溫度頁面，一樣的做法跟call一樣的api

5. 填寫的溫度須跟餐廳細節的這兩個欄位做區間比對，餐廳detail的api已經串接完會放在currentRestaurant裡面
<img width="526" alt="Screen Shot 2022-07-20 at 11 35 40 AM" src="https://user-images.githubusercontent.com/15310175/179890994-e5898662-4738-4602-bdd0-3890017b4a4b.png">

<img width="792" alt="Screen Shot 2022-07-20 at 11 34 07 AM" src="https://user-images.githubusercontent.com/15310175/179890829-abb8ec6f-60d3-421f-8acd-b7ed23ed9fb0.png">

**Comment by shihKaiHung** [comment]
拍照轉成blob()的做法可以參考precool頁面

**Comment by abe1272001** [comment]
@shihKaiHung 
關於 "1. 需鎖定溫度以及拍照完，完成button才能點擊" 是指要先 disable 綠色的完成 button 嗎？看 UI 的行為是會把未完成的提示顯示在 "完成 button" 的 dialog, 且會將確認 button hidden

<img width="309" alt="截圖 2022-07-24 下午11 10 45" src="https://user-images.githubusercontent.com/46858104/180653876-c3f63619-f769-4774-96be-b814e905419d.png">   <img width="311" alt="截圖 2022-07-24 下午11 10 52" src="https://user-images.githubusercontent.com/46858104/180653884-350d0d8f-ad56-4b39-8b2a-6bbc56a6e639.png">

**Comment by shihKaiHung** [comment]
我們直接做disable就好了
